export const ADD_PRODUCT = "ADD_PRODUCT";
export const DISPLAY_PRODUCTS = "DISPLAY_PRODUCTS";
export const UPDATE_STOCK = "UPDATE_STOCK";
export const ADD_TO_CARD = "ADD_TO_CARD";
export const DELETE_FROM_CARD = "DELETE_FROM_CARD";
export const CALCULATE_FINAL_AMOUNT = "CALCULATE_FINAL_AMOUNT";
export const UPDATE_PRODUCT_QUANTITY = "UPDATE_PRODUCT_QUANTITY";
