export const ADD_PRODUCT = "ADD_PRODUCT";
export const DISPLAY_PRODUCTS = "DISPLAY_PRODUCTS";
export const UPDATE_STOCK = "UPDATE_STOCK";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const CALCULATE_FINAL_AMOUNT = "CALCULATE_FINAL_AMOUNT";
export const UPDATE_PRODUCT_QUANTITY = "UPDATE_PRODUCT_QUANTITY";
export const SEARCH_PRODUCTS ='SEARCH_PRODUCTS';
