export const ADD_PRODUCT  = 'ADD_PRODUCT';
export const DISPLAY_PRODUCTS ='DISPLAY_PRODUCTS';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const ADD_TO_CARD ='ADD_TO_CARD';
export const DELETE_FROM_CARD ='DELETE_FROM_CARD';